# Generated by Django 3.1.2 on 2020-10-28 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_analyst', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('identifier', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('_picture', models.BinaryField(blank=True, db_column='picture')),
                ('_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], db_column='gender', max_length=1, null=True)),
                ('language', models.CharField(choices=[('GB', 'English'), ('ES', 'Spanish')], max_length=2)),
                ('username', models.CharField(max_length=20, null=True)),
                ('_schedule', models.DateTimeField(db_column='schedule')),
                ('assigned_doctors', models.ManyToManyField(blank=True, to='howru_models.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('public', models.BooleanField()),
                ('language', models.CharField(choices=[('GB', 'English'), ('ES', 'Spanish')], max_length=2)),
                ('assigned_to_all', models.BooleanField()),
                ('frequency', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('O', 'Once')], default='D', max_length=1)),
                ('priority', models.IntegerField(default=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howru_models.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howru_models.question')),
            ],
        ),
        migrations.CreateModel(
            name='PendingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answering', models.BooleanField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howru_models.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howru_models.patient')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howru_models.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='assigned_questions',
            field=models.ManyToManyField(blank=True, to='howru_models.Question'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AnsweredQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_date', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howru_models.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howru_models.patient')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howru_models.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howru_models.response')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
